spring:
  datasource:
    url: jdbc:postgresql://iaminwoo-db.internal:5432/cd_2025_03_10_prod
    username: postgres
    password: uDHSLNPgIv94h1i
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
logging:
  level:
    com.back: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  site:
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: APP1